<?php
/**
 * The template for displaying all single posts
 *
 * @package Codevani
 */

get_header(); ?>

<!-- Article Header -->
<header class="pt-32 md:pt-28 pb-12 px-4">
    <div class="max-w-4xl mx-auto">
        <div class="flex flex-wrap gap-3 mb-6">
            <?php
            $post_categories = get_the_category();
            if ($post_categories) :
                foreach ($post_categories as $category) :
            ?>
                <span class="bg-purple-100 text-purple-700 px-4 py-2 rounded-full text-sm font-medium">
                    <?php echo esc_html($category->name); ?>
                </span>
            <?php 
                endforeach;
            endif;
            ?>
            <span class="bg-gray-100 text-gray-600 px-4 py-2 rounded-full text-sm">
                <i class="far fa-clock mr-1"></i> <?php echo do_shortcode('[rt_reading_time]'); ?> <?php _e('min read', 'codevani'); ?>
            </span>
            <span class="bg-gray-100 text-gray-600 px-4 py-2 rounded-full text-sm">
                <i class="far fa-calendar mr-1"></i> <?php echo get_the_date('F j, Y'); ?>
            </span>
        </div>
        
        <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-6 leading-tight">
            <?php the_title(); ?>
        </h1>
        
        <?php if (get_the_excerpt()) : ?>
        <p class="text-xl md:text-2xl text-gray-600 mb-8">
            <?php the_excerpt(); ?>
        </p>
        <?php endif; ?>

        <!-- Author Info -->
        <div class="flex items-center gap-4 mb-8 pb-8 border-b border-gray-200">
            <div class="w-16 h-16 rounded-full bg-gradient-to-br from-orange-400 to-purple-500 flex items-center justify-center">
                <?php echo get_avatar(get_the_author_meta('ID'), 48, '', '', array('class' => 'rounded-full')); ?>
            </div>
            <div>
                <p class="font-semibold text-lg"><?php the_author(); ?></p>
                <p class="text-gray-600"><?php echo get_the_author_meta('description') ?: __('Author at', 'codevani') . ' ' . get_bloginfo('name'); ?></p>
            </div>
        </div>

        <!-- Share Buttons -->
        <div class="flex flex-wrap gap-3">
            <button class="share-button bg-blue-600 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-700 transition" onclick="shareOnFacebook()">
                <i class="fab fa-facebook mr-2"></i> <?php _e('Share', 'codevani'); ?>
            </button>
            <button class="share-button bg-sky-500 text-white px-6 py-3 rounded-lg font-medium hover:bg-sky-600 transition" onclick="shareOnTwitter()">
                <i class="fab fa-twitter mr-2"></i> <?php _e('Tweet', 'codevani'); ?>
            </button>
            <button class="share-button bg-blue-700 text-white px-6 py-3 rounded-lg font-medium hover:bg-blue-800 transition" onclick="shareOnLinkedIn()">
                <i class="fab fa-linkedin mr-2"></i> <?php _e('Share', 'codevani'); ?>
            </button>
            <button class="share-button bg-gray-200 text-gray-700 px-6 py-3 rounded-lg font-medium hover:bg-gray-300 transition" onclick="copyLink()">
                <i class="fas fa-link mr-2"></i> <?php _e('Copy Link', 'codevani'); ?>
            </button>
        </div>
    </div>
</header>

<!-- Featured Image -->
<?php if (has_post_thumbnail()) : ?>
<section class="px-4 mb-12">
    <div class="max-w-6xl mx-auto">
        <div class="rounded-3xl overflow-hidden shadow-custom">
            <?php the_post_thumbnail('codevani-blog', array('class' => 'w-full h-96 object-cover')); ?>
        </div>
    </div>
</section>
<?php endif; ?>

<!-- Main Content -->
<article class="px-4 pb-20">
    <div class="max-w-7xl mx-auto">
        <div class="grid grid-cols-1 lg:grid-cols-12 gap-12">
            <!-- Table of Contents (Desktop) -->
            <aside class="hidden lg:block lg:col-span-3">
                <div class="sticky-toc bg-gray-50 rounded-2xl p-6 border border-gray-200">
                    <h3 class="font-bold text-lg mb-4 text-gray-900"><?php _e('Table of Contents', 'codevani'); ?></h3>
                    <nav id="toc-nav">
                        <!-- Table of contents will be generated by JavaScript -->
                    </nav>
                </div>
            </aside>

            <!-- Article Content -->
            <div class="lg:col-span-9">
                <div class="max-w-4xl article-content">
                    <?php
                    while (have_posts()) :
                        the_post();
                        the_content();
                    endwhile;
                    ?>
                </div>
            </div>
        </div>
    </div>
</article>

<!-- Tags -->
<?php
$post_tags = get_the_tags();
if ($post_tags) :
?>
<div class="px-4 pb-12">
    <div class="max-w-4xl mx-auto">
        <div class="mt-12 pt-8 border-t border-gray-200">
            <h3 class="font-bold text-lg mb-4"><?php _e('Tags', 'codevani'); ?></h3>
            <div class="flex flex-wrap gap-2">
                <?php foreach ($post_tags as $tag) : ?>
                    <span class="bg-gray-100 text-gray-700 px-4 py-2 rounded-full text-sm">
                        #<?php echo esc_html($tag->name); ?>
                    </span>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>

<!-- Author Bio -->
<section class="px-4 pb-12">
    <div class="max-w-4xl mx-auto">
        <div class="mt-12 bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-8 border border-purple-100">
            <div class="flex items-start gap-6">
                <div class="w-20 h-20 rounded-full bg-gradient-to-br from-orange-400 to-purple-500 flex items-center justify-center flex-shrink-0">
                    <?php echo get_avatar(get_the_author_meta('ID'), 60, '', '', array('class' => 'rounded-full')); ?>
                </div>
                <div>
                    <h3 class="font-bold text-xl mb-2"><?php _e('About', 'codevani'); ?> <?php the_author(); ?></h3>
                    <p class="text-gray-600 mb-4">
                        <?php echo get_the_author_meta('description') ?: __('This author has not provided a bio yet.', 'codevani'); ?>
                    </p>
                    <div class="flex gap-3">
                        <?php if (get_the_author_meta('twitter')) : ?>
                            <a href="<?php echo esc_url(get_the_author_meta('twitter')); ?>" class="text-gray-600 hover:text-purple-600 transition" target="_blank" rel="noopener">
                                <i class="fab fa-twitter text-xl"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (get_the_author_meta('linkedin')) : ?>
                            <a href="<?php echo esc_url(get_the_author_meta('linkedin')); ?>" class="text-gray-600 hover:text-purple-600 transition" target="_blank" rel="noopener">
                                <i class="fab fa-linkedin text-xl"></i>
                            </a>
                        <?php endif; ?>
                        <?php if (get_the_author_meta('github')) : ?>
                            <a href="<?php echo esc_url(get_the_author_meta('github')); ?>" class="text-gray-600 hover:text-purple-600 transition" target="_blank" rel="noopener">
                                <i class="fab fa-github text-xl"></i>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Related Articles -->
<section class="py-16 px-4 bg-gray-50">
    <div class="max-w-7xl mx-auto">
        <h2 class="text-3xl font-bold mb-8">
            <?php _e('Related', 'codevani'); ?> <span class="gradient-text"><?php _e('Articles', 'codevani'); ?></span>
        </h2>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <?php
            $related_posts = get_posts(array(
                'category__in' => wp_get_post_categories(get_the_ID()),
                'numberposts' => 3,
                'post__not_in' => array(get_the_ID())
            ));

            if ($related_posts) :
                foreach ($related_posts as $post) :
                    setup_postdata($post);
                    $gradient_colors = array(
                        'from-blue-600 to-cyan-600',
                        'from-green-600 to-teal-600',
                        'from-orange-600 to-red-600'
                    );
                    $random_gradient = $gradient_colors[array_rand($gradient_colors)];
            ?>
                <article class="related-card bg-white rounded-2xl overflow-hidden shadow-custom border border-gray-100">
                    <div class="h-48 bg-gradient-to-br <?php echo $random_gradient; ?> flex items-center justify-center">
                        <?php if (has_post_thumbnail()) : ?>
                            <?php the_post_thumbnail('codevani-blog', array('class' => 'w-full h-full object-cover opacity-10')); ?>
                        <?php endif; ?>
                        <i class="fas fa-image text-5xl text-white/30"></i>
                    </div>
                    <div class="p-6">
                        <?php
                        $post_categories = get_the_category();
                        if ($post_categories) :
                        ?>
                            <span class="bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-xs font-medium">
                                <?php echo esc_html($post_categories[0]->name); ?>
                            </span>
                        <?php endif; ?>
                        <h3 class="text-xl font-bold mt-3 mb-2">
                            <a href="<?php the_permalink(); ?>" class="hover:text-purple-600 transition">
                                <?php the_title(); ?>
                            </a>
                        </h3>
                        <p class="text-gray-600 text-sm mb-4"><?php echo wp_trim_words(get_the_excerpt(), 15); ?></p>
                        <a href="<?php the_permalink(); ?>" class="text-purple-600 hover:text-purple-700 font-medium text-sm inline-flex items-center gap-2">
                            <?php _e('Read More', 'codevani'); ?> <i class="fas fa-arrow-right"></i>
                        </a>
                    </div>
                </article>
            <?php
                endforeach;
                wp_reset_postdata();
            else :
                // Fallback related posts
                $fallback_posts = get_posts(array(
                    'numberposts' => 3,
                    'post__not_in' => array(get_the_ID())
                ));
                
                if ($fallback_posts) :
                    foreach ($fallback_posts as $post) :
                        setup_postdata($post);
                        $gradient_colors = array(
                            'from-blue-600 to-cyan-600',
                            'from-green-600 to-teal-600',
                            'from-orange-600 to-red-600'
                        );
                        $random_gradient = $gradient_colors[array_rand($gradient_colors)];
                ?>
                    <article class="related-card bg-white rounded-2xl overflow-hidden shadow-custom border border-gray-100">
                        <div class="h-48 bg-gradient-to-br <?php echo $random_gradient; ?> flex items-center justify-center">
                            <?php if (has_post_thumbnail()) : ?>
                                <?php the_post_thumbnail('codevani-blog', array('class' => 'w-full h-full object-cover opacity-10')); ?>
                            <?php endif; ?>
                            <i class="fas fa-image text-5xl text-white/30"></i>
                        </div>
                        <div class="p-6">
                            <?php
                            $post_categories = get_the_category();
                            if ($post_categories) :
                            ?>
                                <span class="bg-purple-100 text-purple-700 px-3 py-1 rounded-full text-xs font-medium">
                                    <?php echo esc_html($post_categories[0]->name); ?>
                                </span>
                            <?php endif; ?>
                            <h3 class="text-xl font-bold mt-3 mb-2">
                                <a href="<?php the_permalink(); ?>" class="hover:text-purple-600 transition">
                                    <?php the_title(); ?>
                                </a>
                            </h3>
                            <p class="text-gray-600 text-sm mb-4"><?php echo wp_trim_words(get_the_excerpt(), 15); ?></p>
                            <a href="<?php the_permalink(); ?>" class="text-purple-600 hover:text-purple-700 font-medium text-sm inline-flex items-center gap-2">
                                <?php _e('Read More', 'codevani'); ?> <i class="fas fa-arrow-right"></i>
                            </a>
                        </div>
                    </article>
                <?php
                    endforeach;
                    wp_reset_postdata();
                endif;
            endif;
            ?>
        </div>
    </div>
</section>

<!-- Comments Section -->
<?php if (comments_open() || get_comments_number()) : ?>
<section class="py-16 px-4">
    <div class="max-w-4xl mx-auto">
        <?php comments_template(); ?>
    </div>
</section>
<?php endif; ?>

<script>
// Social sharing functions
function shareOnFacebook() {
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(document.title);
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}`, '_blank', 'width=600,height=400');
}

function shareOnTwitter() {
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(document.title);
    window.open(`https://twitter.com/intent/tweet?url=${url}&text=${title}`, '_blank', 'width=600,height=400');
}

function shareOnLinkedIn() {
    const url = encodeURIComponent(window.location.href);
    const title = encodeURIComponent(document.title);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=${url}`, '_blank', 'width=600,height=400');
}

function copyLink() {
    navigator.clipboard.writeText(window.location.href).then(function() {
        alert('<?php _e('Link copied to clipboard!', 'codevani'); ?>');
    });
}

// Generate table of contents
document.addEventListener('DOMContentLoaded', function() {
    const tocNav = document.getElementById('toc-nav');
    const headings = document.querySelectorAll('.article-content h2, .article-content h3, .article-content h4');
    
    if (headings.length > 0 && tocNav) {
        let tocHTML = '<ul class="space-y-2">';
        
        headings.forEach(function(heading, index) {
            const id = 'heading-' + index;
            heading.id = id;
            
            const level = heading.tagName.toLowerCase();
            const indent = level === 'h3' ? 'pl-4' : level === 'h4' ? 'pl-8' : '';
            
            tocHTML += `<li><a href="#${id}" class="toc-item block py-2 text-gray-600 hover:text-purple-600 transition rounded ${indent}">${heading.textContent}</a></li>`;
        });
        
        tocHTML += '</ul>';
        tocNav.innerHTML = tocHTML;
    }
});
</script>

<?php get_footer(); ?>
